### PR TITLE
New BUGS website replaced with React

### PR DESCRIPTION
**Pull request by Kn99HN**
**PR Type:**
New Feature
**Related #'s:**

## Description
- Rebuild BUGS website in React

## Motivation and Context
- The current website looks too .... bluntly bad in comparison to other clubs

## Checklist:
- [x] My code follows the [code style of this project][code-style]
- [x] I have read the [**CONTRIBUTING** document][contributing]

[contributing]: https://github.com/BUGS-NYU/bugs-nyu.github.io/blob/master/.github/CONTRIBUTING.md
[code-style]: https://github.com/BUGS-NYU/bugs-nyu.github.io/tree/master/docs/STYLE_GUIDE.md

### CODE REVIEW

**Comment by maya-b-coding** [comment]
Hey, just noticed "awesome for beginners" under How To Contribute on the home page is misspelled.

**Review by EthanPrintz — COMMENTED** [review]
A few different styling and ux changes I might recommend:
- White and black text within close proximity of each other (home, open source timeline, projects) contrast too much. Try to stick with a consistent light or dark color for text
- Padding should be increased on the home page tiles
- Elements like the tiles that aren't clickable shouldn't have hover states
- Current page should be bolded in the navbar
- I'm not in love with the purple hover states and logo- I think they might look better in white
- We might want to consider finding a way to style or change out the default Google Calendar embed
- We might want to try and fix the horizontal scroll behavior- either figure out what's overflowing or add overflow-x hidden
- I might suggest putting a dark sheet behind the main page content (beneath the titles) to make it more visible and readable while still having a gradient on the sides

**Comment by Kn99HN** [comment]
> Hey, just noticed "awesome for beginners" under How To Contribute on the home page is misspelled.

Thanks. I fixed it!

**Comment by Kn99HN** [comment]
> A few different styling and ux changes I might recommend:
> 
>     * White and black text within close proximity of each other (home, open source timeline, projects) contrast too much. Try to stick with a consistent light or dark color for text
> 
>     * Padding should be increased on the home page tiles
> 
>     * Elements like the tiles that aren't clickable shouldn't have hover states
> 
>     * Current page should be bolded in the navbar
> 
>     * I'm not in love with the purple hover states and logo- I think they might look better in white
> 
>     * We might want to consider finding a way to style or change out the default Google Calendar embed
> 
>     * We might want to try and fix the horizontal scroll behavior- either figure out what's overflowing or add overflow-x hidden
> 
>     * I might suggest putting a dark sheet behind the main page content (beneath the titles) to make it more visible and readable while still having a gradient on the sides

Thanks Ethan!
- Ok, I will change the text color to be more consistent.
- Ok!
- But but but, it looks so cool : <
- Noted
- Yeah, me neither. Was trying to go with NYU theme, but didn't seem to work out so well.
- Yeah, the iframe was weird so I haven't touched Events Page as much
- I actually did but that's a bugs I need to look into
- Not sure how to do this but I can try!

**Comment by A1Liu** [comment]
Let me know when this is ready to merge and I'll merge it and depoy to gh-pages branch

**Comment by Kn99HN** [comment]
Yes, my bad! There are still some minor things I'm currently working on. I'll let you know

**Comment by Kn99HN** [comment]
@A1Liu I believe this is ready for merging. There are still minor things I want to change but for the purpose of a general website, I believe it's good to go!

**Comment by A1Liu** [comment]
Perfect!

**Pull request merged**
