### PR TITLE
Implemented for loop in projects.html

### PR DESCRIPTION
**Pull request by A1Liu**
There was a projects collection and a _projects folder so I did the stuff and made it work. Also, I removed the old projects because they're not recent. I added them to their own files though so it's easy to add them back in if necessary

### CODE REVIEW

**Comment by A1Liu** [comment]
Ok! I fixed it so that order works. Some things I found out in the process:
 - The order of the files when iterating in the Liquid for loop is lexicographical; I think projects in the _projects folder should either be arbitrarily ordered or prefixed with a number in the filename so that order can be controlled
- collections r like really annoying. I don't like them. All the markdown files need front matter in order to be generated - see [this site][collections-jekyll]

Hopefully this change helps!


[collections-jekyll]: https://jekyllrb.com/docs/collections/#add-content

**Comment by A1Liu** [comment]
So my edits kind of remove the HTML styling that already existed, so instead it might be better to use this: 
```html
<div>
	<div>
		<a href="mailto:{{ project.email }}" target="_blank"><h3 class="featurette-heading">{{ project.title }}</h3></a>
		<p><b>Mentor:</b>{{ project.mentor }}<br>
			{{ project.content }}
		</p>
	</div>
</div>
```

**Comment by A1Liu** [comment]
A project file would then look like this:
```markdown
---
title: RCOS Collaboration
mentor: Bradley Brecher
email: bradley.brecher@nyu.edu
---
The team is looking for more members. To get involved, contact him at {{ page.email }}.

This semester BUGS is collaborating with the Rensselaer Polytechnic Institute near Albany, New York. BUGS is bringing one ... so YACS can be adopted for NYU.
```

**Comment by joannakl** [comment]
@A1Liu  Thanks for all the contributions. 
Is there a live version of the website with the changes included that we could use to verify the changes? 

There are many problems on the pages that need fixing. In the future, please create an issue before fixing the problems. This allows future contributors to see the connection between problems and fixes.

**Comment by A1Liu** [comment]
@joannakl The changes should be available to view locally using Jekyll. I think the guide for Jekyll on the README might be a little lacking; I had to jump through quite a few hoops to set it up on my computer, including installing homebrew and using rbenv. I tried to document some of it in #73 , but the doc rewrites that I did aren't very polished so it might not be very helpful.

Also, I'll try to make an issue next time; does this repository have a style guide to follow for issues? 
I made one for the docs (#70 ), but I figured since this contribution isn't really fixing anything as much as it is just implementing something that was probably in the original website plan, an issue wouldn't be necessary.

**Pull request merged**
