### PR TITLE
Move to gatsby

### PR DESCRIPTION
**Pull request by esilverm**
# Description

Converted code to Gatsby JS

I built it on my own github pages but don't want to mess anything up with deploying here so it doesn't work properly, however it *will* work properly if built here. Major changes include:

- Code re-arrangement
- Rewrite of dark mode
- Image optimization for the team page

### CODE REVIEW

**Comment by esilverm** [comment]
Having some problems with responsiveness of the menu and some minor dark mode toggle bugs

I'll fix those up so everything works at the merge

**Comment by esilverm** [comment]
Fixed any existing bugs. A live version can be seen at the following url: https://bugs-site-gatsby-test.vercel.app/

This version of the site performs very well on lighthouse reports (99 performance, 100 accessibility, 100 best practices, 100 SEO) and also works very well on mobile devices.

Please let me know if there are any other changes that should be made before this is merged.

**Comment by esilverm** [comment]
Merged all changes from upstream so there will be no conflicts. You may need to [create a personal access token ](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) and [store it as a repository secret](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets) so this will work for the future.

**Comment by A1Liu** [comment]
I think we might run into problems with github pages and 404 errors if we don't use the HashRouter. Can you use gatsby with local routing on the fragment instead of server routing?

**Comment by A1Liu** [comment]
Hmmm ok looking further into it we might be ok? React routing doesnt work because the file doesn't actually exist, so we get a 404. On gatsby the file should exist, so we should be ok? I'm not sure though.

**Comment by esilverm** [comment]
> I think we might run into problems with github pages and 404 errors if we don't use the HashRouter. Can you use gatsby with local routing on the fragment instead of server routing?

I managed to build it successfully on my own github pages earlier and had no problems. I had to set a prefix since it was on my own github as a project page. This prefix is removed in my current build which is why the github pages build doesn't work on my own account. I am instead using vercel as a hosting site for my code to show that it would work in practice.

**Comment by esilverm** [comment]
> Hmmm ok looking further into it we might be ok? React routing doesnt work because the file doesn't actually exist, so we get a 404. On gatsby the file should exist, so we should be ok? I'm not sure though.

Gatsby does all the routing itself. Since it is a static-site generator there is no need to build in routing unless you have to build client routes (which we aren't using). Routing is done by creating a file within the `/pages` folder. There is no other route configuration needed. Create React App needs to use react router since it is client-side rendered. See the [vercel build](bugs-site-gatsby-test.vercel.app) to see that the code works and will build properly.

**Pull request merged**
