### PR TITLE
Make togglebutton a smaller boi

### PR DESCRIPTION
**Pull request by Kn99HN**

### CODE REVIEW

**Review by esilverm — APPROVED** [review]
Looks good! We could also just simplify it into a single icon that switches between a sun and a moon when clicked, but this is a good fix for right now.

**Review by yuchenliu15 — APPROVED** [review]
LGTM
yea sun and moon icons are easier to understand
also many sites put it on the top right, maybe that's a good option? since for some pages you'll need to scroll down

**Comment by Kn99HN** [comment]
Okie I'll change it

**Comment by Kn99HN** [comment]
The mail svg is a bit weird and I haven't edited it but if u guys can that would be great! Footer is now removed and replaced with sun/moon svg

**Review by yuchenliu15 — APPROVED** [review]
one small thing: in mobile, should it exit the menu after hitting the dark mode? Idk what would be a better UX

everything else looks good!

**Comment by Kn99HN** [comment]
I fixed it now to exit the menu for now. But I think the mobile portion needs some rework in the future

**Review by esilverm — APPROVED** [review]
nice

**Pull request merged**
