### PR TITLE
About Page Formatting, Modularity - Addresses #81

### PR DESCRIPTION
**Pull request by A1Liu**
Improved modularity for about page. Beginning to address #81 by separating the individual entries of each person from the about page itself.

### CODE REVIEW

**Comment by A1Liu** [comment]
This PR simply reduces the clutter in the about.html file, while also improving the modularity by adding a single place to format the contributor entries. Also, this PR makes it much easier to implement something like a contributors.html page, as the collection is in one place.

**Comment by A1Liu** [comment]
The most recent commits fully address #81 . Now, on desktop it looks like this:

screen shot 2018-12-05 at 11 59 18 pm

There are some edge cases that aren't addressed; e.g. how exactly to reformat when the screen changes size, or how to deal with mobile. For now though, I think this works.

**Comment by A1Liu** [comment]
Additional commit to add an "on error" attribute and placeholder image:

screen shot 2018-12-06 at 12 35 30 am

**Review by bradleybrecher — APPROVED** [review]

**Comment by A1Liu** [comment]
The most recent edits have done a few things:

1. **General SASS Modularity** - Used the `dynamic-extend` mixin from toolkit (copy-pasted to leave dependencies untouched), and added a few mixins that might come in handy in the future. I also made sure to check the license and add the licensing info in the file that I declared `dynamic-extend`
2. **About page SASS Modularity** - The about page now uses dynamic-extend and mixins to organize styles into modular groups and reduce repetition of information. Also, mixins created in about page could potentially be used later, maybe in a contributors page?
3. **About page SASS Readability** - Added more comments, tried to move things into separate, reusable sections with hopefully clear purposes.
3. **Mobile support** - The page now uses a media query to reformat the contributors to a vertical orientation when the text is about to wrap past the image. It also resizes the images a little and changes some of the margins. It's not the best, but I don't think we're going to keep this format for that long, so it shouldn't be too big of a deal.

Here's some pictures of what I've done:

Full Desktop:

screen shot 2018-12-17 at 9 14 13 pm

Smaller Desktop:

screen shot 2018-12-17 at 9 14 24 pm

Mobile (simulated on desktop by resizing window):

screen shot 2018-12-17 at 9 14 32 pm

**Pull request merged**
