### PR TITLE
RPI Hackthon announcement

### PR DESCRIPTION
**Pull request by joannakl**
This is a news item (#54) that may be interesting to some of the BUGS followers.

### CODE REVIEW

**Comment by joannakl** [comment]
@A1Liu  can you, please, verify this and merge it. 

Also, how do I add it to the calendar?

**Comment by A1Liu** [comment]
Should be good to go. To make a calendar event you should do a similar process to making a post, using the file `_events/template_event.md` as a guide.

```markdown
---
title: "Title of event"
date: 2017-12-31 # In YYYY-MM-DD format (zero padded)
time: "8pm" # This doesn't need quotes
location: Courant Room 205
---
Markdown text without first title.
```

The data in the file should be automatically added to a file called `data.json` in `/calendar/`, and then used to generate the calendar widget and update the green header at the top of the site.

**Comment by joannakl** [comment]
Thanks.
Looking at this on the website I wonder two things:
1) should this post be made with the date of the making of the post or with the date of the event? Right now it appears with today's date.
2) is there a way to show the first few sentences of the description for the news item with the "More ...." link at the bottom. Not sure if this is a matter of settings or redesign.

**Comment by A1Liu** [comment]
1. For regular posts, the date should be the date of publication. For event posts, the date should be the date of the event. I think for posts Jekyll actually doesn't display them if they're for a date in the future, but the same isn't true for events, as it's not a built in "blog-aware" feature.

2. The first few sentences of the description should be done automatically I think. Jekyll calls it an excerpt, and the paginator should take care of that for us. I'd have to look into it a little more, but it definitely should be nothing more than changing a few lines of templating code. 

Additionally, if you'd like to set a specific breakpoint for the preview, you can do so with the `excerpt_separator` property in the front matter of the document (in between the three dashes). The [documentation][documentation] gives this example:

```markdown
---
excerpt_separator: <!--more-->
---

Excerpt with multiple paragraphs

Here's another paragraph in the excerpt.
<!--more-->
Out-of-excerpt
```

I'll look further into it and give you a better answer once I figure out the infrastructure a little bit better.

[documentation]: https://jekyllrb.com/docs/posts/#post-excerpts

**Pull request merged**
