### PR TITLE
Update Eboard data #227

### LINKED ISSUE #227: Remove Graduating Eboard members
#### Desired Behavior

- Remove Albert, Joanna, Eric and Edmond from Eboard page

#### Mockups

---

**[Contributor Guide](https://github.com/BUGS-NYU/bugs-nyu.github.io/blob/master/contribution/CONTRIBUTING.md)**

### PR DESCRIPTION
**Pull request by Ajinkya-Sonawane**
**Description**
Removed graduating E-board member data.

This PR fixes #227 

**Notes for Reviewers**

### CODE REVIEW

**Review by Kn99HN — CHANGES_REQUESTED** [review]
Howdy!

Thanks for this! Looks great. Sorry for not specifying more in the Issue. Can you move them to this [file]( https://github.com/BUGS-NYU/bugs-nyu.github.io/blob/master/src/data/alumni.js) instead of deleting since they are now alumni?

**Comment by Ajinkya-Sonawane** [comment]
Sure @Kn99HN, I will update the same. What should be the period at the mentioned designation for the outgoing members? (from 2020 to 2021?)
E.g: Albert was BUGS's Vice President from 2020 to 2021

**Comment by Kn99HN** [comment]
> Sure @Kn99HN, I will update the same. What should be the period at the mentioned designation for the outgoing members? (from 2020 to 2021?)
> E.g: Albert was BUGS's Vice President from 2020 to 2021

I think  Albert was BUGS's Vice President is enough but feel free to make the changes and I'll review it!

**Comment by Ajinkya-Sonawane** [comment]
Sure, will commit the changes and open a new PR

**Pull request closed without merging**
